# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_image:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v4
      - name: Build docker image
        id: build
        run: |
          echo "image=hello-world:latest" >> $GITHUB_OUTPUT

  upload-ecs-task:
    needs: [build_image]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Info
        run: |
          echo uploading task definition for image "${{ needs.build_image.steps.build.outputs.image }}"
      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: "dev-definition.json"
          container-name: "test-container"
          image: ${{ needs.build_image.steps.build.outputs.image }}
      - name: Deploy to Amazon ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          cluster: "test-cluster"
          wait-for-service-stability: false

